name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Our.Umbraco.TagHelpers
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: Our.Umbraco.TagHelpers
      
    - name: Dotnet Pack
      run: dotnet pack --output ../build.out/
      working-directory: Our.Umbraco.TagHelpers
      
    - name: Upload nuget file as build artifact      
      uses: actions/upload-artifact@v2
      with:
        name: Nuget Build Output
        path: build.out/
